# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chat_pb2 as chat__pb2


class DataTransferServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Send = channel.unary_unary(
        '/grpc.DataTransferService/Send',
        request_serializer=chat__pb2.Message.SerializeToString,
        response_deserializer=chat__pb2.Ack.FromString,
        )
    self.Ping = channel.unary_stream(
        '/grpc.DataTransferService/Ping',
        request_serializer=chat__pb2.User.SerializeToString,
        response_deserializer=chat__pb2.Message.FromString,
        )


class DataTransferServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Send(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DataTransferServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Send': grpc.unary_unary_rpc_method_handler(
          servicer.Send,
          request_deserializer=chat__pb2.Message.FromString,
          response_serializer=chat__pb2.Ack.SerializeToString,
      ),
      'Ping': grpc.unary_stream_rpc_method_handler(
          servicer.Ping,
          request_deserializer=chat__pb2.User.FromString,
          response_serializer=chat__pb2.Message.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc.DataTransferService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
