# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import raft_pb2 as raft__pb2


class DataTransferServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RaftHeartbit = channel.unary_unary(
        '/grpc.DataTransferService/RaftHeartbit',
        request_serializer=raft__pb2.Table.SerializeToString,
        response_deserializer=raft__pb2.Ack.FromString,
        )
    self.RequestVote = channel.unary_unary(
        '/grpc.DataTransferService/RequestVote',
        request_serializer=raft__pb2.Candidacy.SerializeToString,
        response_deserializer=raft__pb2.CandidacyResponse.FromString,
        )
    self.AddFileLog = channel.unary_unary(
        '/grpc.DataTransferService/AddFileLog',
        request_serializer=raft__pb2.TableLog.SerializeToString,
        response_deserializer=raft__pb2.Ack.FromString,
        )
    self.RequestFileUpload = channel.unary_unary(
        '/grpc.DataTransferService/RequestFileUpload',
        request_serializer=raft__pb2.FileUploadInfo.SerializeToString,
        response_deserializer=raft__pb2.ProxyList.FromString,
        )


class DataTransferServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RaftHeartbit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestVote(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddFileLog(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestFileUpload(self, request, context):
    """Request File upload get back proxy list to
    return proxylist when raft consensus is reached
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DataTransferServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RaftHeartbit': grpc.unary_unary_rpc_method_handler(
          servicer.RaftHeartbit,
          request_deserializer=raft__pb2.Table.FromString,
          response_serializer=raft__pb2.Ack.SerializeToString,
      ),
      'RequestVote': grpc.unary_unary_rpc_method_handler(
          servicer.RequestVote,
          request_deserializer=raft__pb2.Candidacy.FromString,
          response_serializer=raft__pb2.CandidacyResponse.SerializeToString,
      ),
      'AddFileLog': grpc.unary_unary_rpc_method_handler(
          servicer.AddFileLog,
          request_deserializer=raft__pb2.TableLog.FromString,
          response_serializer=raft__pb2.Ack.SerializeToString,
      ),
      'RequestFileUpload': grpc.unary_unary_rpc_method_handler(
          servicer.RequestFileUpload,
          request_deserializer=raft__pb2.FileUploadInfo.FromString,
          response_serializer=raft__pb2.ProxyList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc.DataTransferService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
