# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import file_transfer_pb2 as file__transfer__pb2


class DataTransferServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RaftHeartbit = channel.unary_unary(
        '/grpc.DataTransferService/RaftHeartbit',
        request_serializer=file__transfer__pb2.Table.SerializeToString,
        response_deserializer=file__transfer__pb2.Ack.FromString,
        )
    self.RequestVote = channel.unary_unary(
        '/grpc.DataTransferService/RequestVote',
        request_serializer=file__transfer__pb2.Candidacy.SerializeToString,
        response_deserializer=file__transfer__pb2.CandidacyResponse.FromString,
        )


class DataTransferServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RaftHeartbit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestVote(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DataTransferServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RaftHeartbit': grpc.unary_unary_rpc_method_handler(
          servicer.RaftHeartbit,
          request_deserializer=file__transfer__pb2.Table.FromString,
          response_serializer=file__transfer__pb2.Ack.SerializeToString,
      ),
      'RequestVote': grpc.unary_unary_rpc_method_handler(
          servicer.RequestVote,
          request_deserializer=file__transfer__pb2.Candidacy.FromString,
          response_serializer=file__transfer__pb2.CandidacyResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc.DataTransferService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
